// Code generated by "stringer -type=FloodHaz"; DO NOT EDIT.

package comment

import "strconv"

const _FloodHaz_name = "XFIVEAAEFLOODWAYLEVEE"

var _FloodHaz_index = [...]uint8{0, 1, 5, 6, 8, 16, 21}

func (i FloodHaz) String() string {
	if i < 0 || i >= FloodHaz(len(_FloodHaz_index)-1) {
		return "FloodHaz(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FloodHaz_name[_FloodHaz_index[i]:_FloodHaz_index[i+1]]
}
