// Code generated by "stringer -type=streetClass"; DO NOT EDIT.

package comment

import "strconv"

const _streetClass_name = "ResidentialMinorResidentialCollectorCommercialMinorArterialArterial"

var _streetClass_index = [...]uint8{0, 11, 27, 36, 46, 59, 67}

func (i streetClass) String() string {
	if i < 0 || i >= streetClass(len(_streetClass_index)-1) {
		return "streetClass(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _streetClass_name[_streetClass_index[i]:_streetClass_index[i+1]]
}
